pipeline {
    agent any
    stages {
        stage('preparing stuff') {
            steps {
                echo 'preparing bits and pieces'
            }
        }
        stage('call pipeline1') {
            steps {
                echo 'calling pl2'
                build job: 'pipeline2', parameters: [string(name: 'run', value: env.BUILD_URL)]
            }
        }
    }
}
