pipeline {
    agent any
 
    options {
	buildDiscarder(logRotator(numToKeepStr: '10'))
    }
 
    parameters {
	string(name: 'run',
	       description: "the job build url to process")
    }

    stages{
        stage('prepare stuff') {
            steps {
                echo "preparing stuff.."
            }
        }
        stage('run stuff') {
            steps {
                echo "pp2 for "+params.run+"!"
            }
        }
    }
}
